### ISSUE TITLE
下载报错，发现了个问题

### ISSUE THREAD

**Issue by dgyiOS** [xietao3/Study-Plan#2]
![1](https://user-images.githubusercontent.com/37854650/54521872-d34dc980-49a6-11e9-9cb4-98b2c08a4c18.jpg)

**Comment by xietao3** [comment]
> ![1](https://user-images.githubusercontent.com/37854650/54521872-d34dc980-49a6-11e9-9cb4-98b2c08a4c18.jpg)

忘记删了，之前竟然没有报错😂
